### ISSUE TITLE
switch from existing rtinst to this fork

### ISSUE THREAD

**Issue by TitusTom** [stickz/rtinst#3]
Hello,

As title says, how can we switch from an existing install to this fork?

**Comment by stickz** [comment]
hi @TitusTom you should be able to just run the setup again. Please feel free let me know if this does not work for you.

**Comment by wietvergiet** [comment]
I did the migration and it changes the ssh port to the default 22 while the original script kept my custom ssh port when rerunning it. This could cause major issues on remote systems if you don't realise this change and have port 22 closed.

**Comment by stickz** [comment]
hi @wietvergiet Thank you for this feedback. I have fixed this problem. It will no longer change your SSH port. If it's already changed, it will keep it there. https://github.com/stickz/rtinst/commit/ba1121ac37844b42528ebe5c62188cb9e03fba39

Could you try the migration again and let me know how it goes? I really want to make this work for people, so they can utilize my changes without having to reinstall everything.
