### ISSUE TITLE
Issue with curl

### ISSUE THREAD

**Issue by shnaps** [stickz/rtinst#4]
It seems like the current install script will fail for any curl version because of problems linking libcurl. This is my log for a new VPS, clean and just installed debian 9.
```
curl -V
curl 7.80.0 (i686-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
WARNING: curl and libcurl versions do not match. Functionality may be affected.
curl: symbol lookup error: curl: undefined symbol: curl_mime_free
```
I assume curl itself is installed but libcurl is not/not linked properly?

**Comment by stickz** [comment]
Debian 9 is too old. You need an operating system which comes with libcurl 7.56 or newer for this script. You may experience performance issues on rTorrent without c-ares. To add this feature, we must compile curl ourselves.

**Comment by shnaps** [comment]
I would love to get 10 or 11 but my VPS provider doesn't have such an option. 
I'm wondering if there is any way to manually define libcurl .so version which comes with curl binary while compiling? 
There is https://github.com/curl/curl/issues/4448 which is related but too bad that I have 0 experience with c/c++ build tools.
Also https://github.com/curl/curl/blob/master/docs/HTTP3.md has -rpath example, which seems like an exact thing needed.

**Comment by stickz** [comment]
Okay, I updated the script to make the curl build pass on Debian 9. I downgraded the version of curl to 7.52 for Debian 9 to match libcurl. I was not able to get ruTorrent working on my Debian 9 cloud server though. Perhaps, you'll be able to diagnose this issue.

**Comment by AdmLars** [comment]
Your commit on feb 6, `ff6f2c0abf3291d3963adad3d0022013c0a11dd5` broke rutorrent on fresh install.
Had to downgrade the conf/ru.config to get it working again.

Btw, thank you for your work on maintaining this script!
