### ISSUE TITLE
Varnish stops the installation/update

### ISSUE THREAD

**Issue by amlopin** [stickz/rtinst#7]
Hi folks, I am updating my rtinst script with this update. Firstly many thanks for the update, really nice.
Well the issue I am having its that as you can see from my log, "varnish" is getting mad with everything. I am not very good reading logs and in linux. 
Would you mind to have a look and guide me to solve the issue with the install/update

I have got a dedicate server in OVH, Debian 9 installed. The script has been working very well in the last 2 years and today I tried to make some updates and now everything is failing.

Many thanks

Installing Log file https://pastebin.com/kcRf5TfT

**Comment by stickz** [comment]
Hi @amlopin Are you able to upgrade to Debian 10? The script is designed for this operating system version.

I just patched the script for ruTorrent version 4.0.2 for you in https://github.com/stickz/rtinst/commit/1d6416535b943096901aa392e3a6d7809517cd27 .

**Comment by amlopin** [comment]
Wow amazing bro! I just did the upgrade to debian 10 and I run the script until it stuck "Setting permissions, Starting services", then ssh session was closed. I checked the log and there were plenty of error lol

Would you mind to have a look??

https://pastebin.com/KFymCp53

Also I would like to say thank you so much for updating the script as it seems the original git is dead (no the developer lol I dont know if he is ok by the way, I meant the script haha sorry for the joke :D)

**Comment by amlopin** [comment]
Hi again. I just finished a second run of the script and now it was completed (took 3 hours) but it is not working as after the first try.
Here ssh log: https://pastebin.com/RXi0dWSm
Here real install log https://pastebin.com/eNLB134s

I hope it can be resolved without a fresh install :D

Many thanks for looking it

**Comment by stickz** [comment]
Please run `sudo rtupdate` to reinstall libtorrent & rtorrent. The libtorrent installation was broken. I resolved the problem.

**Comment by amlopin** [comment]
Hi many thanks for the support. I was unable to use "rtupdate", I had: "rtorrent NOT installed
This script is for upgrading/downgrading only, not for initial install"

So I had to use "sudo rtinst" to install rtorrent but after I run it twice, always I got the following error:
"Starting rtorrent..........
WARNING: Unable to start rtorrent
/usr/local/bin/rtinst: line 1036: rtorrent: command not found"

This is the install log: https://pastebin.com/SqZrv7HB

Many thanks

**Comment by amlopin** [comment]
Hi, just to report that I got another dedicated and I run the script, and getting the same issue:
"Starting rtorrent..........
WARNING: Unable to start rtorrent
/usr/local/bin/rtinst: line 1036: rtorrent: command not found"

Many thanks

**Comment by stickz** [comment]
I just spun up a cloud server and fixed the script. It was more complicated than anticipated. libtorrent was still acting up.
```
Installing libtorrent
/usr/local/bin/rtupdate: line 201: ./autogen.sh: No such file or directory
/usr/local/bin/rtupdate: line 205: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

Please rerun the script again from the beginning. I also took about 15 to 30 seconds off the source file compilations by adding multi-threaded link time optimizations. https://github.com/stickz/rtinst/commit/831e28eca7e74c9d9ad99fadc085e4bc325f82c4

**Comment by amlopin** [comment]
Hi, many thanks for the support and looking into the issues. 

The error I got now it´s:
```
Configuring SSH
Configuring nginx
Configuring Varnish Cache
cp: cannot create regular file '/usr/lib/systemd/system/varnish.service': No such file or directory
```

The point is that Varnish is running but in other folder

```
 systemctl status varnish
* varnish.service - Varnish HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2023-03-13 00:34:14 CET; 2min 55s ago
```

Many thanks

**Comment by amlopin** [comment]
Hi again, it stuck now in this line, it´s rtorrent installation. I dont know if you need the full log or just where it makes the error. 
Many thanks

```
../rak/priority_queue_default.h:56:95: note: in C++11 destructors default to noexcept
depbase=`echo command_ip.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -O3 -fipa-pta -march=native -fexcess-precision=fast -freciprocal-math -flto=2 -MT command_ip.o -MD -MP -MF $depbase.Tpo -c -o command_ip.o command_ip.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo command_helpers.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -O3 -fipa-pta -march=native -fexcess-precision=fast -freciprocal-math -flto=2 -MT command_helpers.o -MD -MP -MF $depbase.Tpo -c -o command_helpers.o command_helpers.cc &&\
mv -f $depbase.Tpo $depbase.Po
make[2]: *** [Makefile:1043: command_ip.o] Hangup
make[2]: *** [Makefile:1043: command_helpers.o] Hangup
make[1]: *** wait: No child processes.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: *** wait: No child processes.  Stop.
make: *** [Makefile:385: all] Error 2
```

**Comment by amlopin** [comment]
I re run it and got the log for better troubleshooting. Thanks
https://pastebin.com/QisMQMNm

**Comment by stickz** [comment]
This problem is related to ARM, where the make file hangs. I unfortunately cannot provide support for ARM because I don't have a testing environment to test the script. I would recommend using X86, or choosing an alternative install script like swizzin.

**Comment by amlopin** [comment]
> This problem is related to ARM, where the make file hangs. I unfortunately cannot provide support for ARM because I don't have a testing environment to test the script. I would recommend using X86, or choosing an alternative install script like swizzin.

Ok. Many thanks
